// Lightweight country dial-code dataset.
// Loaded LAZILY (dynamic import) by CountryCodeSelect so it stays out of the
// initial bundle. No flags/images — just Romanian name + dial code + ISO2.

export interface Country {
  name: string
  dialCode: string
  iso2: string
}

const countries: Country[] = [
  { name: 'Afganistan', dialCode: '+93', iso2: 'AF' },
  { name: 'Africa de Sud', dialCode: '+27', iso2: 'ZA' },
  { name: 'Albania', dialCode: '+355', iso2: 'AL' },
  { name: 'Algeria', dialCode: '+213', iso2: 'DZ' },
  { name: 'Andorra', dialCode: '+376', iso2: 'AD' },
  { name: 'Angola', dialCode: '+244', iso2: 'AO' },
  { name: 'Anguilla', dialCode: '+1264', iso2: 'AI' },
  { name: 'Antigua și Barbuda', dialCode: '+1268', iso2: 'AG' },
  { name: 'Arabia Saudită', dialCode: '+966', iso2: 'SA' },
  { name: 'Argentina', dialCode: '+54', iso2: 'AR' },
  { name: 'Armenia', dialCode: '+374', iso2: 'AM' },
  { name: 'Aruba', dialCode: '+297', iso2: 'AW' },
  { name: 'Australia', dialCode: '+61', iso2: 'AU' },
  { name: 'Austria', dialCode: '+43', iso2: 'AT' },
  { name: 'Azerbaidjan', dialCode: '+994', iso2: 'AZ' },
  { name: 'Bahamas', dialCode: '+1242', iso2: 'BS' },
  { name: 'Bahrain', dialCode: '+973', iso2: 'BH' },
  { name: 'Bangladesh', dialCode: '+880', iso2: 'BD' },
  { name: 'Barbados', dialCode: '+1246', iso2: 'BB' },
  { name: 'Belgia', dialCode: '+32', iso2: 'BE' },
  { name: 'Belize', dialCode: '+501', iso2: 'BZ' },
  { name: 'Benin', dialCode: '+229', iso2: 'BJ' },
  { name: 'Bermuda', dialCode: '+1441', iso2: 'BM' },
  { name: 'Bhutan', dialCode: '+975', iso2: 'BT' },
  { name: 'Bielorusia', dialCode: '+375', iso2: 'BY' },
  { name: 'Bolivia', dialCode: '+591', iso2: 'BO' },
  { name: 'Bosnia și Herțegovina', dialCode: '+387', iso2: 'BA' },
  { name: 'Botswana', dialCode: '+267', iso2: 'BW' },
  { name: 'Brazilia', dialCode: '+55', iso2: 'BR' },
  { name: 'Brunei', dialCode: '+673', iso2: 'BN' },
  { name: 'Bulgaria', dialCode: '+359', iso2: 'BG' },
  { name: 'Burkina Faso', dialCode: '+226', iso2: 'BF' },
  { name: 'Burundi', dialCode: '+257', iso2: 'BI' },
  { name: 'Cambodgia', dialCode: '+855', iso2: 'KH' },
  { name: 'Camerun', dialCode: '+237', iso2: 'CM' },
  { name: 'Canada', dialCode: '+1', iso2: 'CA' },
  { name: 'Capul Verde', dialCode: '+238', iso2: 'CV' },
  { name: 'Cehia', dialCode: '+420', iso2: 'CZ' },
  { name: 'Chile', dialCode: '+56', iso2: 'CL' },
  { name: 'China', dialCode: '+86', iso2: 'CN' },
  { name: 'Ciad', dialCode: '+235', iso2: 'TD' },
  { name: 'Cipru', dialCode: '+357', iso2: 'CY' },
  { name: 'Coasta de Fildeș', dialCode: '+225', iso2: 'CI' },
  { name: 'Columbia', dialCode: '+57', iso2: 'CO' },
  { name: 'Comore', dialCode: '+269', iso2: 'KM' },
  { name: 'Congo', dialCode: '+242', iso2: 'CG' },
  { name: 'Congo (RD)', dialCode: '+243', iso2: 'CD' },
  { name: 'Coreea de Nord', dialCode: '+850', iso2: 'KP' },
  { name: 'Coreea de Sud', dialCode: '+82', iso2: 'KR' },
  { name: 'Costa Rica', dialCode: '+506', iso2: 'CR' },
  { name: 'Croația', dialCode: '+385', iso2: 'HR' },
  { name: 'Cuba', dialCode: '+53', iso2: 'CU' },
  { name: 'Curaçao', dialCode: '+599', iso2: 'CW' },
  { name: 'Danemarca', dialCode: '+45', iso2: 'DK' },
  { name: 'Djibouti', dialCode: '+253', iso2: 'DJ' },
  { name: 'Dominica', dialCode: '+1767', iso2: 'DM' },
  { name: 'Ecuador', dialCode: '+593', iso2: 'EC' },
  { name: 'Egipt', dialCode: '+20', iso2: 'EG' },
  { name: 'El Salvador', dialCode: '+503', iso2: 'SV' },
  { name: 'Elveția', dialCode: '+41', iso2: 'CH' },
  { name: 'Emiratele Arabe Unite', dialCode: '+971', iso2: 'AE' },
  { name: 'Eritreea', dialCode: '+291', iso2: 'ER' },
  { name: 'Estonia', dialCode: '+372', iso2: 'EE' },
  { name: 'Eswatini', dialCode: '+268', iso2: 'SZ' },
  { name: 'Etiopia', dialCode: '+251', iso2: 'ET' },
  { name: 'Fiji', dialCode: '+679', iso2: 'FJ' },
  { name: 'Filipine', dialCode: '+63', iso2: 'PH' },
  { name: 'Finlanda', dialCode: '+358', iso2: 'FI' },
  { name: 'Franța', dialCode: '+33', iso2: 'FR' },
  { name: 'Gabon', dialCode: '+241', iso2: 'GA' },
  { name: 'Gambia', dialCode: '+220', iso2: 'GM' },
  { name: 'Georgia', dialCode: '+995', iso2: 'GE' },
  { name: 'Germania', dialCode: '+49', iso2: 'DE' },
  { name: 'Ghana', dialCode: '+233', iso2: 'GH' },
  { name: 'Gibraltar', dialCode: '+350', iso2: 'GI' },
  { name: 'Grecia', dialCode: '+30', iso2: 'GR' },
  { name: 'Grenada', dialCode: '+1473', iso2: 'GD' },
  { name: 'Groenlanda', dialCode: '+299', iso2: 'GL' },
  { name: 'Guadelupa', dialCode: '+590', iso2: 'GP' },
  { name: 'Guam', dialCode: '+1671', iso2: 'GU' },
  { name: 'Guatemala', dialCode: '+502', iso2: 'GT' },
  { name: 'Guineea', dialCode: '+224', iso2: 'GN' },
  { name: 'Guineea Ecuatorială', dialCode: '+240', iso2: 'GQ' },
  { name: 'Guineea-Bissau', dialCode: '+245', iso2: 'GW' },
  { name: 'Guyana', dialCode: '+592', iso2: 'GY' },
  { name: 'Haiti', dialCode: '+509', iso2: 'HT' },
  { name: 'Honduras', dialCode: '+504', iso2: 'HN' },
  { name: 'Hong Kong', dialCode: '+852', iso2: 'HK' },
  { name: 'India', dialCode: '+91', iso2: 'IN' },
  { name: 'Indonezia', dialCode: '+62', iso2: 'ID' },
  { name: 'Insulele Marshall', dialCode: '+692', iso2: 'MH' },
  { name: 'Insulele Solomon', dialCode: '+677', iso2: 'SB' },
  { name: 'Irak', dialCode: '+964', iso2: 'IQ' },
  { name: 'Iran', dialCode: '+98', iso2: 'IR' },
  { name: 'Irlanda', dialCode: '+353', iso2: 'IE' },
  { name: 'Islanda', dialCode: '+354', iso2: 'IS' },
  { name: 'Israel', dialCode: '+972', iso2: 'IL' },
  { name: 'Italia', dialCode: '+39', iso2: 'IT' },
  { name: 'Jamaica', dialCode: '+1876', iso2: 'JM' },
  { name: 'Japonia', dialCode: '+81', iso2: 'JP' },
  { name: 'Iordania', dialCode: '+962', iso2: 'JO' },
  { name: 'Kazahstan', dialCode: '+7', iso2: 'KZ' },
  { name: 'Kenya', dialCode: '+254', iso2: 'KE' },
  { name: 'Kârgâzstan', dialCode: '+996', iso2: 'KG' },
  { name: 'Kiribati', dialCode: '+686', iso2: 'KI' },
  { name: 'Kosovo', dialCode: '+383', iso2: 'XK' },
  { name: 'Kuweit', dialCode: '+965', iso2: 'KW' },
  { name: 'Laos', dialCode: '+856', iso2: 'LA' },
  { name: 'Lesotho', dialCode: '+266', iso2: 'LS' },
  { name: 'Letonia', dialCode: '+371', iso2: 'LV' },
  { name: 'Liban', dialCode: '+961', iso2: 'LB' },
  { name: 'Liberia', dialCode: '+231', iso2: 'LR' },
  { name: 'Libia', dialCode: '+218', iso2: 'LY' },
  { name: 'Liechtenstein', dialCode: '+423', iso2: 'LI' },
  { name: 'Lituania', dialCode: '+370', iso2: 'LT' },
  { name: 'Luxemburg', dialCode: '+352', iso2: 'LU' },
  { name: 'Macao', dialCode: '+853', iso2: 'MO' },
  { name: 'Macedonia de Nord', dialCode: '+389', iso2: 'MK' },
  { name: 'Madagascar', dialCode: '+261', iso2: 'MG' },
  { name: 'Malaysia', dialCode: '+60', iso2: 'MY' },
  { name: 'Malawi', dialCode: '+265', iso2: 'MW' },
  { name: 'Maldive', dialCode: '+960', iso2: 'MV' },
  { name: 'Mali', dialCode: '+223', iso2: 'ML' },
  { name: 'Malta', dialCode: '+356', iso2: 'MT' },
  { name: 'Maroc', dialCode: '+212', iso2: 'MA' },
  { name: 'Martinica', dialCode: '+596', iso2: 'MQ' },
  { name: 'Mauritania', dialCode: '+222', iso2: 'MR' },
  { name: 'Mauritius', dialCode: '+230', iso2: 'MU' },
  { name: 'Mexic', dialCode: '+52', iso2: 'MX' },
  { name: 'Micronezia', dialCode: '+691', iso2: 'FM' },
  { name: 'Monaco', dialCode: '+377', iso2: 'MC' },
  { name: 'Mongolia', dialCode: '+976', iso2: 'MN' },
  { name: 'Muntenegru', dialCode: '+382', iso2: 'ME' },
  { name: 'Mozambic', dialCode: '+258', iso2: 'MZ' },
  { name: 'Myanmar', dialCode: '+95', iso2: 'MM' },
  { name: 'Namibia', dialCode: '+264', iso2: 'NA' },
  { name: 'Nauru', dialCode: '+674', iso2: 'NR' },
  { name: 'Nepal', dialCode: '+977', iso2: 'NP' },
  { name: 'Nicaragua', dialCode: '+505', iso2: 'NI' },
  { name: 'Niger', dialCode: '+227', iso2: 'NE' },
  { name: 'Nigeria', dialCode: '+234', iso2: 'NG' },
  { name: 'Norvegia', dialCode: '+47', iso2: 'NO' },
  { name: 'Noua Zeelandă', dialCode: '+64', iso2: 'NZ' },
  { name: 'Noua Caledonie', dialCode: '+687', iso2: 'NC' },
  { name: 'Olanda', dialCode: '+31', iso2: 'NL' },
  { name: 'Oman', dialCode: '+968', iso2: 'OM' },
  { name: 'Pakistan', dialCode: '+92', iso2: 'PK' },
  { name: 'Palau', dialCode: '+680', iso2: 'PW' },
  { name: 'Palestina', dialCode: '+970', iso2: 'PS' },
  { name: 'Panama', dialCode: '+507', iso2: 'PA' },
  { name: 'Papua Noua Guinee', dialCode: '+675', iso2: 'PG' },
  { name: 'Paraguay', dialCode: '+595', iso2: 'PY' },
  { name: 'Peru', dialCode: '+51', iso2: 'PE' },
  { name: 'Polinezia Franceză', dialCode: '+689', iso2: 'PF' },
  { name: 'Polonia', dialCode: '+48', iso2: 'PL' },
  { name: 'Portugalia', dialCode: '+351', iso2: 'PT' },
  { name: 'Porto Rico', dialCode: '+1787', iso2: 'PR' },
  { name: 'Qatar', dialCode: '+974', iso2: 'QA' },
  { name: 'Regatul Unit', dialCode: '+44', iso2: 'GB' },
  { name: 'Republica Centrafricană', dialCode: '+236', iso2: 'CF' },
  { name: 'Republica Dominicană', dialCode: '+1809', iso2: 'DO' },
  { name: 'Republica Moldova', dialCode: '+373', iso2: 'MD' },
  { name: 'Réunion', dialCode: '+262', iso2: 'RE' },
  { name: 'România', dialCode: '+40', iso2: 'RO' },
  { name: 'Ruanda', dialCode: '+250', iso2: 'RW' },
  { name: 'Rusia', dialCode: '+7', iso2: 'RU' },
  { name: 'Saint Kitts și Nevis', dialCode: '+1869', iso2: 'KN' },
  { name: 'Saint Lucia', dialCode: '+1758', iso2: 'LC' },
  { name: 'Saint Vincent și Grenadinele', dialCode: '+1784', iso2: 'VC' },
  { name: 'Samoa', dialCode: '+685', iso2: 'WS' },
  { name: 'San Marino', dialCode: '+378', iso2: 'SM' },
  { name: 'Sao Tomé și Príncipe', dialCode: '+239', iso2: 'ST' },
  { name: 'Senegal', dialCode: '+221', iso2: 'SN' },
  { name: 'Serbia', dialCode: '+381', iso2: 'RS' },
  { name: 'Seychelles', dialCode: '+248', iso2: 'SC' },
  { name: 'Sierra Leone', dialCode: '+232', iso2: 'SL' },
  { name: 'Singapore', dialCode: '+65', iso2: 'SG' },
  { name: 'Siria', dialCode: '+963', iso2: 'SY' },
  { name: 'Slovacia', dialCode: '+421', iso2: 'SK' },
  { name: 'Slovenia', dialCode: '+386', iso2: 'SI' },
  { name: 'Somalia', dialCode: '+252', iso2: 'SO' },
  { name: 'Spania', dialCode: '+34', iso2: 'ES' },
  { name: 'Sri Lanka', dialCode: '+94', iso2: 'LK' },
  { name: 'Statele Unite', dialCode: '+1', iso2: 'US' },
  { name: 'Sudan', dialCode: '+249', iso2: 'SD' },
  { name: 'Sudanul de Sud', dialCode: '+211', iso2: 'SS' },
  { name: 'Suedia', dialCode: '+46', iso2: 'SE' },
  { name: 'Surinam', dialCode: '+597', iso2: 'SR' },
  { name: 'Tadjikistan', dialCode: '+992', iso2: 'TJ' },
  { name: 'Tanzania', dialCode: '+255', iso2: 'TZ' },
  { name: 'Thailanda', dialCode: '+66', iso2: 'TH' },
  { name: 'Taiwan', dialCode: '+886', iso2: 'TW' },
  { name: 'Timorul de Est', dialCode: '+670', iso2: 'TL' },
  { name: 'Togo', dialCode: '+228', iso2: 'TG' },
  { name: 'Tonga', dialCode: '+676', iso2: 'TO' },
  { name: 'Trinidad și Tobago', dialCode: '+1868', iso2: 'TT' },
  { name: 'Tunisia', dialCode: '+216', iso2: 'TN' },
  { name: 'Turcia', dialCode: '+90', iso2: 'TR' },
  { name: 'Turkmenistan', dialCode: '+993', iso2: 'TM' },
  { name: 'Tuvalu', dialCode: '+688', iso2: 'TV' },
  { name: 'Ucraina', dialCode: '+380', iso2: 'UA' },
  { name: 'Uganda', dialCode: '+256', iso2: 'UG' },
  { name: 'Ungaria', dialCode: '+36', iso2: 'HU' },
  { name: 'Uruguay', dialCode: '+598', iso2: 'UY' },
  { name: 'Uzbekistan', dialCode: '+998', iso2: 'UZ' },
  { name: 'Vanuatu', dialCode: '+678', iso2: 'VU' },
  { name: 'Vatican', dialCode: '+379', iso2: 'VA' },
  { name: 'Venezuela', dialCode: '+58', iso2: 'VE' },
  { name: 'Vietnam', dialCode: '+84', iso2: 'VN' },
  { name: 'Yemen', dialCode: '+967', iso2: 'YE' },
  { name: 'Zambia', dialCode: '+260', iso2: 'ZM' },
  { name: 'Zimbabwe', dialCode: '+263', iso2: 'ZW' },
]

export default countries
